In [1]:
import numpy as np

In [2]:
ratings=np.array([[5,2,4.5],[1,4,1],[4,1,4],[2,2,1.5]])
print(ratings)

[[5.  2.  4.5]
 [1.  4.  1. ]
 [4.  1.  4. ]
 [2.  2.  1.5]]


In [3]:
u,s,vt=np.linalg.svd(ratings)

In [4]:
print(u.shape)
print(u)
print()
print(s.shape)
print(s)
print()
print(vt.shape)
print(vt)

(4, 4)
[[-0.70691924 -0.1948368   0.2986126  -0.61084722]
 [-0.28594129  0.88348348 -0.35038429 -0.12216944]
 [-0.5679376  -0.34133294 -0.56756738  0.48867778]
 [-0.30975741  0.25492624  0.68258965  0.61084722]]

(3,)
[9.87708006 3.58089108 0.34714345]

(3, 3)
[[-0.67953309 -0.37916631 -0.62806663]
 [-0.26423027  0.92512723 -0.27262056]
 [ 0.68441007 -0.01930048 -0.72884178]]


In [5]:
Sigma=np.zeros((4,3))
Sigma[:3,:3]=np.diag(s)
print(Sigma)

[[9.87708006 0.         0.        ]
 [0.         3.58089108 0.        ]
 [0.         0.         0.34714345]
 [0.         0.         0.        ]]


In [6]:
print(u@Sigma@vt)

[[5.  2.  4.5]
 [1.  4.  1. ]
 [4.  1.  4. ]
 [2.  2.  1.5]]


In [7]:
s[-1]=0
Sigma=np.zeros((4,3))
Sigma[:3,:3]=np.diag(s)
print(Sigma)

[[9.87708006 0.         0.        ]
 [0.         3.58089108 0.        ]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]


In [8]:
print(u@Sigma@vt)

[[4.92905309 2.00200071 4.57555277]
 [1.08324727 3.99765241 0.91134834]
 [4.13484747 0.99619728 3.85639827]
 [1.83782457 2.00457337 1.67270382]]
