In [1]:
import torch

In [2]:
Qs = torch.rand((5,2))
print(Qs)

tensor([[0.0504, 0.6981],
        [0.1032, 0.4717],
        [0.1700, 0.0886],
        [0.6742, 0.5631],
        [0.8857, 0.9020]])


In [4]:
torch.max(Qs,dim=1)[0]

tensor([0.6981, 0.4717, 0.1700, 0.6742, 0.9020])

In [ ]:
actions = torch.randint(2,(5,1))
print(actions)

In [ ]:
Qs.gather(1,actions)

In [5]:
BATCH_SIZE=10
torch.zeros(BATCH_SIZE)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])